# Generated by Django 4.2.10 on 2024-02-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
