# Generated by Django 4.2.10 on 2024-02-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApi', '0002_usertable_delete_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='gender',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
