# Generated by Django 4.2.10 on 2024-02-26 05:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('emp_id', models.CharField(max_length=6)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_phone_number', models.CharField(max_length=10)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_address', models.TextField()),
            ],
        ),
    ]
