# Generated by Django 4.2.10 on 2024-02-28 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_update_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('product_created_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('product_type', models.CharField(max_length=255)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('product_delete_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
